version: '3.9'

services:
  order-service:
    image: 'order-service:latest'
    build:
      context: .
    container_name:
      'order-service-container'
    depends_on:
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/${DB_SCHEMA}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - MICROSERVICES_URL_USER_SERVICE=${USER_SERVICE_URL}
    ports:
      - "8083:80"

  order-db:
    image: postgres
    container_name: 'order-db'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_SCHEMA}