spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
        order_deletes: true

security:
  jwt-key: ${JWT_KEY}

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true