spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
        order_deletes: true