spring:
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true