spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true